### ISSUE TITLE
Issue while building boost depend sources

### ISSUE THREAD

**Issue by tejeshanil** [NeuraiProject/Neurai#1]
#### If so, please list the steps to reproduce below:
1. switch to depends directory
2. Run make command which results in Boost sources build failure.

### Expected behaviour
Boost sources are failed to build

### Actual behaviour
Boost sources should build without any source changes

### Screenshots.
![image](https://github.com/NeuraiProject/Neurai/assets/16666666/c1ff95c8-500b-42df-8380-2e6a8f463fb2)

### What version of Neurai are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Ubuntu 22.04 .2 LTS
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.

[log.txt](https://github.com/NeuraiProject/Neurai/files/11858951/log.txt)

### proposed fix:
Update **boost/1_71_0-2f955e3c438/boost/thread/pthread/thread_data.hpp**  at line 60 

- #if PTHREAD_STACK_MIN > 0
+ #ifdef PTHREAD_STACK_MIN > 0

**Comment by tejeshanil** [comment]
Boost version used : boost_1_71_0.tar.bz2

Downloads/neurai/Neurai-1.0.2$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

/Downloads/neurai/Neurai-1.0.2$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1\~22.04.1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-aYxV0E/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-aYxV0E/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)

**Comment by NeuraiProject** [comment]
Hi, I've been doing some tests for a few days and it seems that the problem is with Ubuntu 22.04 to compile some of the libraries. I have tried in other similar projects and the same thing happens.

If you use Ubuntu 20.04 or even debian, it works without problems and I think the best option right now is to use Docker to compile the binaries in the OS needed. 

You have in the docs folder one to create Linux binaries that you may find useful.

[https://github.com/NeuraiProject/Neurai/tree/main/doc/docker](https://github.com/NeuraiProject/Neurai/tree/main/doc/docker)
