### ISSUE TITLE
Where is your gitignore file?

### ISSUE THREAD

**Issue by dimmarvel** [NeuraiProject/Neurai#2]
### Describe the issue
After the build there is a lot of garbage left which is displayed in the git status, write a simple gitignor, this will greatly simplify the process of using git.

### Actual behaviour
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/Makefile.am

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Makefile
	Makefile.in
	aclocal.m4
	autom4te.cache/
	build-aux/compile
	build-aux/config.guess
	build-aux/config.sub
	build-aux/depcomp
	build-aux/install-sh
	build-aux/ltmain.sh
	build-aux/m4/libtool.m4
	build-aux/m4/ltoptions.m4
	build-aux/m4/ltsugar.m4
	build-aux/m4/ltversion.m4
	build-aux/m4/lt~obsolete.m4
	build-aux/missing
	build-aux/test-driver
	confdefs.h
	config.log
	config.status
	configure
	configure~
	contrib/devtools/split-debug.sh
	doc/man/Makefile
	doc/man/Makefile.in
	libneuraiconsensus.pc
	libtool
	share/qt/Info.plist
	share/setup.nsi
	src/.gitignore
	src/bench/bench_neurai
	src/config/neurai-config.h
	src/config/neurai-config.h.in
	src/config/stamp-h1
	src/neurai-cli
	src/neuraid
	src/obj/
	src/qt/forms/ui_addressbookpage.h
	src/qt/forms/ui_askpassphrasedialog.h
	src/qt/forms/ui_assetcontroldialog.h
	src/qt/forms/ui_assetsdialog.h
	src/qt/forms/ui_coincontroldialog.h
	src/qt/forms/ui_createassetdialog.h
	src/qt/forms/ui_debugwindow.h
	src/qt/forms/ui_editaddressdialog.h
	src/qt/forms/ui_helpmessagedialog.h
	src/qt/forms/ui_intro.h
	src/qt/forms/ui_mnemonicdialog1.h
	src/qt/forms/ui_mnemonicdialog2.h
	src/qt/forms/ui_mnemonicdialog3.h
	src/qt/forms/ui_modaloverlay.h
	src/qt/forms/ui_openuridialog.h
	src/qt/forms/ui_optionsdialog.h
	src/qt/forms/ui_overviewpage.h
	src/qt/forms/ui_receivecoinsdialog.h
	src/qt/forms/ui_receiverequestdialog.h
	src/qt/forms/ui_reissueassetdialog.h
	src/qt/forms/ui_restrictedassetsdialog.h
	src/qt/forms/ui_restrictedassignqualifier.h
	src/qt/forms/ui_restrictedfreezeaddress.h
	src/qt/forms/ui_sendassetsentry.h
	src/qt/forms/ui_sendcoinsdialog.h
	src/qt/forms/ui_sendcoinsentry.h
	src/qt/forms/ui_signverifymessagedialog.h
	src/qt/forms/ui_transactiondescdialog.h
	src/qt/intro.moc
	src/qt/moc_addressbookpage.cpp
	src/qt/moc_addresstablemodel.cpp
	src/qt/moc_askpassphrasedialog.cpp
	src/qt/moc_assetcontroldialog.cpp
	src/qt/moc_assetcontroltreewidget.cpp
	src/qt/moc_assetfilterproxy.cpp
	src/qt/moc_assetsdialog.cpp
	src/qt/moc_assettablemodel.cpp
	src/qt/moc_bantablemodel.cpp
	src/qt/moc_callback.cpp
	src/qt/moc_clientmodel.cpp
	src/qt/moc_coincontroldialog.cpp
	src/qt/moc_coincontroltreewidget.cpp
	src/qt/moc_createassetdialog.cpp
	src/qt/moc_csvmodelwriter.cpp
	src/qt/moc_darkstyle.cpp
	src/qt/moc_editaddressdialog.cpp
	src/qt/moc_guiutil.cpp
	src/qt/moc_intro.cpp
	src/qt/moc_macdockiconhandler.cpp
	src/qt/moc_macnotificationhandler.cpp
	src/qt/moc_mnemonicdialog.cpp
	src/qt/moc_modaloverlay.cpp
	src/qt/moc_myrestrictedassettablemodel.cpp
	src/qt/moc_neuraiaddressvalidator.cpp
	src/qt/moc_neuraiamountfield.cpp
	src/qt/moc_neuraigui.cpp
	src/qt/moc_neuraiunits.cpp
	src/qt/moc_notificator.cpp
	src/qt/moc_openuridialog.cpp
	src/qt/moc_optionsdialog.cpp
	src/qt/moc_optionsmodel.cpp
	src/qt/moc_overviewpage.cpp
	src/qt/moc_paymentserver.cpp
	src/qt/moc_peertablemodel.cpp
	src/qt/moc_qvalidatedlineedit.cpp
	src/qt/moc_qvaluecombobox.cpp
	src/qt/moc_receivecoinsdialog.cpp
	src/qt/moc_receiverequestdialog.cpp
	src/qt/moc_recentrequeststablemodel.cpp
	src/qt/moc_reissueassetdialog.cpp
	src/qt/moc_restrictedassetsdialog.cpp
	src/qt/moc_restrictedassignqualifier.cpp
	src/qt/moc_restrictedfreezeaddress.cpp
	src/qt/moc_rpcconsole.cpp
	src/qt/moc_sendassetsentry.cpp
	src/qt/moc_sendcoinsdialog.cpp
	src/qt/moc_sendcoinsentry.cpp
	src/qt/moc_signverifymessagedialog.cpp
	src/qt/moc_splashscreen.cpp
	src/qt/moc_trafficgraphwidget.cpp
	src/qt/moc_transactiondesc.cpp
	src/qt/moc_transactiondescdialog.cpp
	src/qt/moc_transactionfilterproxy.cpp
	src/qt/moc_transactiontablemodel.cpp
	src/qt/moc_transactionview.cpp
	src/qt/moc_utilitydialog.cpp
	src/qt/moc_walletframe.cpp
	src/qt/moc_walletmodel.cpp
	src/qt/moc_walletview.cpp
	src/qt/neurai-qt
	src/qt/neurai.moc
	src/qt/neuraiamountfield.moc
	src/qt/overviewpage.moc
	src/qt/rpcconsole.moc
	src/qt/test/moc_compattests.cpp
	src/qt/test/moc_rpcnestedtests.cpp
	src/qt/test/moc_uritests.cpp
	src/qt/test/test_neurai-qt
	src/rpc/notifyer.cpp
	src/rpc/notifyer.h
	src/secp256k1/build-aux/compile
	src/secp256k1/build-aux/config.guess
	src/secp256k1/build-aux/config.sub
	src/secp256k1/build-aux/depcomp
	src/secp256k1/build-aux/install-sh
	src/secp256k1/build-aux/ltmain.sh
	src/secp256k1/build-aux/m4/libtool.m4
	src/secp256k1/build-aux/m4/ltoptions.m4
	src/secp256k1/build-aux/m4/ltsugar.m4
	src/secp256k1/build-aux/m4/ltversion.m4
	src/secp256k1/build-aux/m4/lt~obsolete.m4
	src/secp256k1/build-aux/missing
	src/secp256k1/build-aux/test-driver
	src/secp256k1/gen_context
	src/secp256k1/libsecp256k1.pc
	src/secp256k1/src/ecmult_static_context.h
	src/secp256k1/src/libsecp256k1-config.h
	src/secp256k1/src/libsecp256k1-config.h.in
	src/secp256k1/src/stamp-h1
	src/test/test_neurai
	src/test/test_neurai_fuzzy
	src/test/test_neurai_hash
	src/univalue/build-aux/
	src/univalue/pc/libunivalue-uninstalled.pc
	src/univalue/pc/libunivalue.pc
	src/univalue/stamp-h1
	src/univalue/univalue-config.h
	src/univalue/univalue-config.h.in
	test/config.ini

no changes added to commit (use "git add" and/or "git commit -a")

### What version of Neurai are you using?
Latest in repo

**Comment by NeuraiProject** [comment]
Hi, we add gitignore file

https://github.com/NeuraiProject/Neurai/blob/main/.gitignore
